spring:
  datasource:
    batch:
      # Spring Batch ??????MySQL??????????
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:63306/test_db3?userCursorFetch=true
      username: test
      password: testpass
      # Spring Batch ???????H2DB ??????????
    #      driver-class-name: org.h2.Driver
    #      url: jdbc:h2:mem:batch_db:Mode=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    #      username: test
    #      password: testpass
    copy-source:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:63306/test_db1?userCursorFetch=true
      username: test
      password: testpass
      fetchsize: 1000
    copy-to:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:63306/test_db2?userCursorFetch=true
      username: test
      password: testpass
      fetchsize: 1000
  batch:
    jdbc:
      # ????????????????????
      initialize-schema: always

